// Artwork data, exhibitions, CV - bilingual where it matters
window.SITE_DATA = {
  paintings: [
    { img: "images/p03-1.jpg", title: "House of the Sun", medium_de: "Acryl auf Leinwand", medium_en: "Acrylic on canvas", size: "125 × 150 cm", year: "2025", note_de: "Privatsammlung, New York", note_en: "Private collection, New York" },
    { img: "images/p07-1.jpg", title: "Red Mountain", medium_de: "Acryl auf Leinwand", medium_en: "Acrylic on canvas", size: "112 × 114 cm", year: "2026" },
    { img: "images/p06-1.jpg", title: "Wings of the Sun", medium_de: "Acryl auf Leinwand", medium_en: "Acrylic on canvas", size: "71 × 79 cm", year: "2026" },
    { img: "images/p04-1.jpg", title: "Flying Horses, Blue", medium_de: "Acryl auf Leinwand", medium_en: "Acrylic on canvas", size: "116 × 95 cm", year: "2024" },
    { img: "images/p09-1.jpg", title: "Green Horses", medium_de: "Acryl, Ölkreide auf Leinwand", medium_en: "Acrylic, oil pastel on canvas", size: "92 × 68 cm", year: "2024" },
    { img: "images/p08-1.jpg", title: "No Name", medium_de: "Acryl auf Leinwand", medium_en: "Acrylic on canvas", size: "160 × 140 cm", year: "2023" },
    { img: "images/p10-1.jpg", title: "Astronaut", medium_de: "Acryl und Ölkreide auf Leinwand", medium_en: "Acrylic and oil pastel on canvas", size: "100 × 150 cm", year: "2022" },
    { img: "images/p11-1.jpg", title: "Concert", medium_de: "Acryl auf Leinwand", medium_en: "Acrylic on canvas", size: "120 × 160 cm", year: "2023" },
    { img: "images/p05-1.jpg", title: "Olive Tree", medium_de: "Mischtechnik auf Papier", medium_en: "Mixed media on paper", size: "95 × 112 cm", year: "2023" },
  ],
  prints: [
    { img: "images/p13-1.jpg", title: "Flying Horses, Blue", medium_de: "Siebdruck auf Leinwand", medium_en: "Screenprint on canvas", size: "32 × 26,5 cm", year: "2026" },
    { img: "images/p14-1.jpg", title: "House of the Sun", medium_de: "Tinte auf Papier, Linolschnitt", medium_en: "Ink on paper, linocut", size: "15 × 21 cm", year: "2024" },
  ],
  ceramics: [
    { img: "images/p15-1.jpg", title: "Vase with Horses", medium_de: "Keramik", medium_en: "Ceramic", size: "28 × 21 cm", year: "2025" },
    { img: "images/p16-1.jpg", title: "Bird with Candles, Chanukkia", medium_de: "Keramik", medium_en: "Ceramic", size: "32 × 18,5 cm", year: "2023" },
    { img: "images/p17-1.jpg", title: "Bird", medium_de: "Keramik", medium_en: "Ceramic", size: "32 × 18,5 cm", year: "2023" },
    { img: "images/p17-2.jpg", title: "Bird", medium_de: "Keramik", medium_en: "Ceramic", size: "32 × 18,5 cm", year: "2023" },
    { img: "images/p18-1.jpg", title: "Horse with Wings, Horse without Wings", medium_de: "Keramik", medium_en: "Ceramic", size: "11 × 12 cm", year: "2024" },
    { img: "images/p18-2.jpg", title: "Friends, Kerzenhalter", medium_de: "Keramik, glasiert", medium_en: "Glazed ceramic", size: "24 × 11 cm", year: "2025" },
    { img: "images/p19-1.jpg", title: "Relief with Horses", medium_de: "Keramik", medium_en: "Ceramic", size: "11 × 12 cm", year: "2024" },
    { img: "images/p19-2.jpg", title: "Cat", medium_de: "Keramik, glasiert", medium_en: "Glazed ceramic", size: "21 cm h, Ø 10 cm", year: "2026" },
    { img: "images/p20-1.jpg", title: "Seder Plate", medium_de: "Keramik, glasiert", medium_en: "Glazed ceramic", size: "Ø 28 cm", year: "2025" },
    { img: "images/p20-2.jpg", title: "Seder Plate", medium_de: "Keramik, glasiert", medium_en: "Glazed ceramic", size: "Ø 28 cm", year: "2025" },
    { img: "images/p21-1.jpg", title: "Gefäß", medium_de: "Keramik, glasiert", medium_en: "Glazed ceramic", size: "28 × 14 cm", year: "2026" },
    { img: "images/p21-2.jpg", title: "Horses and Shells", medium_de: "Keramik", medium_en: "Ceramic", size: "—", year: "2025" },
  ],
  photography: [
    { img: "images/p26-1.jpg", title: "Living With The Stars", medium_de: "Fine Art Inkjet Print", medium_en: "Fine art inkjet print", size: "120 × 170 cm", year: "2021" },
    { img: "images/p28-1.jpg", title: "Living With The Stars", medium_de: "Fine Art Inkjet auf Hahnemühle Photo Rag", medium_en: "Fine art inkjet on Hahnemühle Photo Rag", size: "40 × 60 cm", year: "2021", note_de: "Privatsammlung, Melbourne", note_en: "Private collection, Melbourne" },
    { img: "images/p29-1.jpg", title: "Living With The Stars", medium_de: "Fine Art Inkjet Print", medium_en: "Fine art inkjet print", size: "120 × 170 cm", year: "2021" },
    { img: "images/p30-1.jpg", title: "C.G. Boerner Gallery, New York", medium_de: "Digitaldruck - C.G. Boerner, New York", medium_en: "Digital print - C.G. Boerner, New York", size: "45 × 60 cm", year: "2020" },
  ],
  exhibitionViews: [
    { img: "images/p27-1.jpg", title: "Living With The Stars", medium_de: "Videoinstallation, 3:40 min loop", medium_en: "Video installation, 3:40 min loop", size: "Das Weisse Haus, Wien", year: "2022" },
    { img: "images/p23-1.jpg", title: "Blowin' in the Wind", medium_de: "Ausstellungsansicht", medium_en: "Exhibition view", size: "Pinacoteca do Ceará, Fortaleza, Brasilien", year: "2022–23" },
    { img: "images/p24-1.jpg", title: "Blowin' in the Wind", medium_de: "Ausstellungsansicht", medium_en: "Exhibition view", size: "Pinacoteca do Ceará, Fortaleza, Brasilien", year: "2022–23" },
    { img: "images/p25-1.jpg", title: "Blowin' in the Wind", medium_de: "Ausstellungsansicht", medium_en: "Exhibition view", size: "Pinacoteca do Ceará, Fortaleza, Brasilien", year: "2022–23" },
  ],
  knSpace: [
    { img: "images/kn01-1.png", title: "KN – Space for Art in Context", medium_de: "Künstlerinitiative · Galerie- & Projektraum, Berlin", medium_en: "Artist initiative · Gallery & project space, Berlin", size: "Gründerin, Direktorin & Kuratorin", year: "2014–18", note_de: "Ausstellungsansicht", note_en: "Installation view" },
  ],
  publications: [
    { img: "images/p31-1.jpg", title: "June - A Road Trip, USA", year: "2013", de: "Künstlerbuch · Auflage 50 · Leipzig · Dummy Award Shortlist 2013 · Fotobookfestival Kassel · Art Book Salon, Wien", en: "Artist book · Edition of 50 · Leipzig · Dummy Award Shortlist 2013 · Fotobookfestival Kassel · Art Book Salon, Vienna", view_de: "Vorderseite", view_en: "Front" },
    { img: "images/p31-2.jpg", title: "June - A Road Trip, USA", year: "2013", de: "Künstlerbuch · Auflage 50 · Leipzig · Dummy Award Shortlist 2013 · Fotobookfestival Kassel · Art Book Salon, Wien", en: "", view_de: "Rückseite", view_en: "Back" },
    { img: "images/p31-3.jpg", title: "Mistake or Miracle", year: "2021", de: "Mit Gedichten von Dayna Grosz · Gestaltung Meeusontwerpt, Amsterdam · Auflage 100 · ISBN 978-3-00-070325-6 · Dummy Award Shortlist 2021", en: "With poems by Dayna Grosz · Design by Meeusontwerpt, Amsterdam · Edition of 100 · ISBN 978-3-00-070325-6 · Dummy Award Shortlist 2021", view_de: "Vorderseite", view_en: "Front" },
    { img: "images/p31-4.jpg", title: "Mistake or Miracle", year: "2021", de: "Mit Gedichten von Dayna Grosz · Gestaltung Meeusontwerpt, Amsterdam · Auflage 100 · ISBN 978-3-00-070325-6 · Dummy Award Shortlist 2021", en: "", view_de: "Rückseite", view_en: "Back" },
    { img: "images/p31-5.jpg", title: "León d'Oro - Look at Me", year: "2011", de: "Hrsg. Mona Schieren & Andrea Sick · Verlag für Moderne Kunst, Nürnberg · La Biennale, Venedig 2011", en: "Eds. Mona Schieren & Andrea Sick · Verlag für Moderne Kunst, Nuremberg · La Biennale, Venice 2011", view_de: "Vorderseite", view_en: "Front" },
    { img: "images/p31-6.jpg", title: "León d'Oro - Look at Me", year: "2011", de: "Hrsg. Mona Schieren & Andrea Sick · Verlag für Moderne Kunst, Nürnberg · La Biennale, Venedig 2011", en: "", view_de: "Rückseite", view_en: "Back" },
  ],
  // CV exhibitions
  exhibitions: [
    { year: "2025", de: "Bridges – Magazinpräsentation, Galerie ZeitZone, Berlin", en: "Bridges – Magazine launch, Galerie ZeitZone, Berlin" },
    { year: "2024", de: "Will We Hide Our Love Forever – Gruppenausstellung, Eisen74, Berlin", en: "Will We Hide Our Love Forever – Group exhibition, Eisen74, Berlin" },
    { year: "2022–23", de: "Photoszene – Buchausstellung, The PhotoBook Museum, Köln", en: "Photoszene – Book exhibition, The PhotoBook Museum, Cologne" },
    { year: "2022–23", de: "Blowin' in the Wind – Gruppenausst., Fotofestival Solar, Pinacoteca do Ceará, Fortaleza, Brasilien", en: "Blowin' in the Wind – Group exhibition, Fotofestival Solar, Pinacoteca do Ceará, Fortaleza, Brazil" },
    { year: "2022–23", de: "Mistake or Miracle – Buchpräsentation & Ausstellung, Studio Das Weisse Haus, Wien", en: "Mistake or Miracle – Book launch & exhibition, Studio Das Weisse Haus, Vienna" },
    { year: "2021", de: "Mistake or Miracle – Buchpräsentation & Ausstellung, Motto Distribution, Berlin", en: "Mistake or Miracle – Book launch & exhibition, Motto Distribution, Berlin" },
    { year: "2021", de: "Secret Space – Einzelausstellung, Studio68, Berlin", en: "Secret Space – Solo exhibition, Studio68, Berlin" },
    { year: "2020", de: "Covid-19 Diaries – Gruppenausstellung, Lovaas Projects, München", en: "Covid-19 Diaries – Group exhibition, Lovaas Projects, Munich" },
    { year: "2020", de: "Zwang – Gruppenausstellung, C.G. Boerner Gallery, New York", en: "Zwang – Group exhibition, C.G. Boerner Gallery, New York" },
    { year: "2020", de: "Spring Break Art Show LA – Gruppenausstellung, Los Angeles", en: "Spring Break Art Show LA – Group exhibition, Los Angeles" },
    { year: "2016–17", de: "This Is a Free Zone – NBGK, Berlin", en: "This Is a Free Zone – NBGK, Berlin" },
    { year: "2016–17", de: "Diamonds Are for Ever – GfZK, Leipzig", en: "Diamonds Are for Ever – GfZK, Leipzig" },
    { year: "2016–17", de: "Remember It / Know the Ways / Cloudbusting – KN – Space for Art in Context, Berlin", en: "Remember It / Know the Ways / Cloudbusting – KN – Space for Art in Context, Berlin" },
    { year: "2013–14", de: "June – Einzelausstellung, White Cube, Halle 14, Baumwollspinnerei, Leipzig", en: "June – Solo exhibition, White Cube, Halle 14, Baumwollspinnerei, Leipzig" },
    { year: "2013–14", de: "June – Fotobookfestival Kassel", en: "June – Fotobookfestival Kassel" },
    { year: "2013–14", de: "Never Get to Know – Einzelausstellung, KN Gallery, Berlin", en: "Never Get to Know – Solo exhibition, KN Gallery, Berlin" },
    { year: "2013–14", de: "Italienische Reise – Werkschauhalle, Baumwollspinnerei, Leipzig", en: "Italienische Reise – Werkschauhalle, Baumwollspinnerei, Leipzig" },
    { year: "2011", de: "Look at Me (León d'Oro) – Künstlerbuchpräsentation, La Biennale, Venedig", en: "Look at Me (León d'Oro) – Artist book launch, La Biennale, Venice" },
    { year: "2009–10", de: "Taboo – Deloitte, Luxemburg", en: "Taboo – Deloitte, Luxembourg" },
    { year: "2009–10", de: "Wicked Game – HfK Bremen", en: "Wicked Game – HfK Bremen" },
    { year: "2009–10", de: "Überwintern – Abfertigung, Bremen", en: "Überwintern – Abfertigung, Bremen" },
    { year: "2009–10", de: "The Birds You Killed – HGB Leipzig", en: "The Birds You Killed – HGB Leipzig" },
  ],
  education: [
    { year: "2009–13", de: "MFA - Bildende Kunst & Fotografie, Hochschule für Grafik und Buchkunst (HGB) Leipzig · Klasse Prof. Tina Bara", en: "MFA - Fine Art & Photography, Academy of Fine Arts (HGB) Leipzig · Class of Prof. Tina Bara" },
    { year: "2006–09", de: "Kommunikationsdesign & Fotografie, Hochschule für Künste (HfK) Bremen · bei Prof. Peter Bialobrzeski", en: "Communication Design & Photography, Hochschule für Künste (HfK) Bremen · with Prof. Peter Bialobrzeski" },
  ],
  experience: [
    { year: "2014–18", de: "Gründerin, Direktorin & Kuratorin · KN - Space for Art in Context, Berlin", en: "Founder, Director & Curator · KN - Space for Art in Context, Berlin" },
  ],
  cvPublications: [
    { year: "2025", de: "Bridges Magazine · Berlin", en: "Bridges Magazine · Berlin" },
    { year: "2021", de: "Miracle or Mistake · Kunst- & Poesiebuch (mit Dayna Grosz) · Dummy Award Shortlist · Berlin", en: "Miracle or Mistake · Art & poetry book (with Dayna Grosz) · Dummy Award Shortlist · Berlin" },
    { year: "2017", de: "Nichtsalsschönheit Nr. 4 · Magazin · Berlin", en: "Nichtsalsschönheit No. 4 · Magazine · Berlin" },
    { year: "2015", de: "Nichtsalsschönheit · Magazin · Berlin", en: "Nichtsalsschönheit · Magazine · Berlin" },
    { year: "2014", de: "Diary of a Dog · Künstlerbuch · Hybriden Verlag, Berlin", en: "Diary of a Dog · Artist book · Hybriden Verlag, Berlin" },
    { year: "2013", de: "June · Künstlerbuch · Dummy Award Shortlist · Leipzig", en: "June · Artist book · Dummy Award Shortlist · Leipzig" },
    { year: "2011", de: "León d'Oro – Look at Me · S. 156–163 · Verlag für Moderne Kunst, Nürnberg", en: "León d'Oro – Look at Me · pp. 156–163 · Verlag für Moderne Kunst, Nuremberg" },
    { year: "2009", de: "Fashionably Depressed · Ventil Verlag, Mainz · S. 104–120", en: "Fashionably Depressed · Ventil Verlag, Mainz · pp. 104–120" },
    { year: "2008", de: "Teneriffa · Verbrecher Verlag, Berlin · S. 143–151", en: "Teneriffa · Verbrecher Verlag, Berlin · pp. 143–151" },
  ],
  curating: [
    { year: "2017", de: "Remember It · Nichtsalsschönheit Nr. 4 – KN – Space for Art in Context, Berlin", en: "Remember It · Nichtsalsschönheit No. 4 – KN – Space for Art in Context, Berlin" },
    { year: "2015", de: "Cloudbusting · Show Me How · Just for One Day – KN, Berlin", en: "Cloudbusting · Show Me How · Just for One Day – KN, Berlin" },
    { year: "2014", de: "The Night Bell with Lightning · Fliegt Schnell Laut Summend – KN, Berlin", en: "The Night Bell with Lightning · Fliegt Schnell Laut Summend – KN, Berlin" },
    { year: "2012", de: "No Animals Were Harmed During This Production – HGB Leipzig", en: "No Animals Were Harmed During This Production – HGB Leipzig" },
  ],
};
